server.port: 31001
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/testDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true
      format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

